### ISSUE TITLE
Open existing Storage File

### ISSUE THREAD

**Issue by rishavbhowmik** [rishavbhowmik/storage-engine-rust#2]
So far we support creating for new storage file and initialisation of storage header and then read/write blocks. But now we need to open existing storage file, read storage header, search empty blocks and then read/write blocks.

### ToDo

- [x] **implement `Storage.get_storage_header`** - read data set using `Storage.get_storage_header`
- [x] **implement `Storage.read_storage_block_headers`** - count total used blocks and update `Storage.free_blocks` for indexing empty blocks
- [x] **implement `Storage::open`** - opens existing StorageFile - _use `Storage::open_file_writer` with truncate false_ https://github.com/rishavbhowmik/storage-engine-rust/blob/a7302bb7ac9b126622d156c2954b0b8ab278ccac/src/storage/mod.rs#L120
